//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCYN.Print.StockServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StockServiceReference.IStockService")]
    public interface IStockService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockService/GetPrice", ReplyAction="http://tempuri.org/IStockService/GetPriceResponse")]
        XCYN.Service.WCF.StockPrice GetPrice(string ticker);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IStockService/GetPrice", ReplyAction="http://tempuri.org/IStockService/GetPriceResponse")]
        System.IAsyncResult BeginGetPrice(string ticker, System.AsyncCallback callback, object asyncState);
        
        XCYN.Service.WCF.StockPrice EndGetPrice(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockService/SetPrice", ReplyAction="http://tempuri.org/IStockService/SetPriceResponse")]
        double SetPrice(XCYN.Service.WCF.StockPrice price);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IStockService/SetPrice", ReplyAction="http://tempuri.org/IStockService/SetPriceResponse")]
        System.IAsyncResult BeginSetPrice(XCYN.Service.WCF.StockPrice price, System.AsyncCallback callback, object asyncState);
        
        double EndSetPrice(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IStockService/DoBigAnalysisFast")]
        void DoBigAnalysisFast();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, AsyncPattern=true, Action="http://tempuri.org/IStockService/DoBigAnalysisFast")]
        System.IAsyncResult BeginDoBigAnalysisFast(System.AsyncCallback callback, object asyncState);
        
        void EndDoBigAnalysisFast(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockService/DoBigAnslysisSlow", ReplyAction="http://tempuri.org/IStockService/DoBigAnslysisSlowResponse")]
        void DoBigAnslysisSlow();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IStockService/DoBigAnslysisSlow", ReplyAction="http://tempuri.org/IStockService/DoBigAnslysisSlowResponse")]
        System.IAsyncResult BeginDoBigAnslysisSlow(System.AsyncCallback callback, object asyncState);
        
        void EndDoBigAnslysisSlow(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStockServiceChannel : XCYN.Print.StockServiceReference.IStockService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetPriceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetPriceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public XCYN.Service.WCF.StockPrice Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((XCYN.Service.WCF.StockPrice)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SetPriceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SetPriceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public double Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StockServiceClient : System.ServiceModel.ClientBase<XCYN.Print.StockServiceReference.IStockService>, XCYN.Print.StockServiceReference.IStockService {
        
        private BeginOperationDelegate onBeginGetPriceDelegate;
        
        private EndOperationDelegate onEndGetPriceDelegate;
        
        private System.Threading.SendOrPostCallback onGetPriceCompletedDelegate;
        
        private BeginOperationDelegate onBeginSetPriceDelegate;
        
        private EndOperationDelegate onEndSetPriceDelegate;
        
        private System.Threading.SendOrPostCallback onSetPriceCompletedDelegate;
        
        private BeginOperationDelegate onBeginDoBigAnalysisFastDelegate;
        
        private EndOperationDelegate onEndDoBigAnalysisFastDelegate;
        
        private System.Threading.SendOrPostCallback onDoBigAnalysisFastCompletedDelegate;
        
        private BeginOperationDelegate onBeginDoBigAnslysisSlowDelegate;
        
        private EndOperationDelegate onEndDoBigAnslysisSlowDelegate;
        
        private System.Threading.SendOrPostCallback onDoBigAnslysisSlowCompletedDelegate;
        
        public StockServiceClient() {
        }
        
        public StockServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StockServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetPriceCompletedEventArgs> GetPriceCompleted;
        
        public event System.EventHandler<SetPriceCompletedEventArgs> SetPriceCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DoBigAnalysisFastCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DoBigAnslysisSlowCompleted;
        
        public XCYN.Service.WCF.StockPrice GetPrice(string ticker) {
            return base.Channel.GetPrice(ticker);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetPrice(string ticker, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetPrice(ticker, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public XCYN.Service.WCF.StockPrice EndGetPrice(System.IAsyncResult result) {
            return base.Channel.EndGetPrice(result);
        }
        
        private System.IAsyncResult OnBeginGetPrice(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string ticker = ((string)(inValues[0]));
            return this.BeginGetPrice(ticker, callback, asyncState);
        }
        
        private object[] OnEndGetPrice(System.IAsyncResult result) {
            XCYN.Service.WCF.StockPrice retVal = this.EndGetPrice(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetPriceCompleted(object state) {
            if ((this.GetPriceCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetPriceCompleted(this, new GetPriceCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetPriceAsync(string ticker) {
            this.GetPriceAsync(ticker, null);
        }
        
        public void GetPriceAsync(string ticker, object userState) {
            if ((this.onBeginGetPriceDelegate == null)) {
                this.onBeginGetPriceDelegate = new BeginOperationDelegate(this.OnBeginGetPrice);
            }
            if ((this.onEndGetPriceDelegate == null)) {
                this.onEndGetPriceDelegate = new EndOperationDelegate(this.OnEndGetPrice);
            }
            if ((this.onGetPriceCompletedDelegate == null)) {
                this.onGetPriceCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetPriceCompleted);
            }
            base.InvokeAsync(this.onBeginGetPriceDelegate, new object[] {
                        ticker}, this.onEndGetPriceDelegate, this.onGetPriceCompletedDelegate, userState);
        }
        
        public double SetPrice(XCYN.Service.WCF.StockPrice price) {
            return base.Channel.SetPrice(price);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginSetPrice(XCYN.Service.WCF.StockPrice price, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSetPrice(price, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public double EndSetPrice(System.IAsyncResult result) {
            return base.Channel.EndSetPrice(result);
        }
        
        private System.IAsyncResult OnBeginSetPrice(object[] inValues, System.AsyncCallback callback, object asyncState) {
            XCYN.Service.WCF.StockPrice price = ((XCYN.Service.WCF.StockPrice)(inValues[0]));
            return this.BeginSetPrice(price, callback, asyncState);
        }
        
        private object[] OnEndSetPrice(System.IAsyncResult result) {
            double retVal = this.EndSetPrice(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSetPriceCompleted(object state) {
            if ((this.SetPriceCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SetPriceCompleted(this, new SetPriceCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SetPriceAsync(XCYN.Service.WCF.StockPrice price) {
            this.SetPriceAsync(price, null);
        }
        
        public void SetPriceAsync(XCYN.Service.WCF.StockPrice price, object userState) {
            if ((this.onBeginSetPriceDelegate == null)) {
                this.onBeginSetPriceDelegate = new BeginOperationDelegate(this.OnBeginSetPrice);
            }
            if ((this.onEndSetPriceDelegate == null)) {
                this.onEndSetPriceDelegate = new EndOperationDelegate(this.OnEndSetPrice);
            }
            if ((this.onSetPriceCompletedDelegate == null)) {
                this.onSetPriceCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSetPriceCompleted);
            }
            base.InvokeAsync(this.onBeginSetPriceDelegate, new object[] {
                        price}, this.onEndSetPriceDelegate, this.onSetPriceCompletedDelegate, userState);
        }
        
        public void DoBigAnalysisFast() {
            base.Channel.DoBigAnalysisFast();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginDoBigAnalysisFast(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDoBigAnalysisFast(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndDoBigAnalysisFast(System.IAsyncResult result) {
            base.Channel.EndDoBigAnalysisFast(result);
        }
        
        private System.IAsyncResult OnBeginDoBigAnalysisFast(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginDoBigAnalysisFast(callback, asyncState);
        }
        
        private object[] OnEndDoBigAnalysisFast(System.IAsyncResult result) {
            this.EndDoBigAnalysisFast(result);
            return null;
        }
        
        private void OnDoBigAnalysisFastCompleted(object state) {
            if ((this.DoBigAnalysisFastCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DoBigAnalysisFastCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DoBigAnalysisFastAsync() {
            this.DoBigAnalysisFastAsync(null);
        }
        
        public void DoBigAnalysisFastAsync(object userState) {
            if ((this.onBeginDoBigAnalysisFastDelegate == null)) {
                this.onBeginDoBigAnalysisFastDelegate = new BeginOperationDelegate(this.OnBeginDoBigAnalysisFast);
            }
            if ((this.onEndDoBigAnalysisFastDelegate == null)) {
                this.onEndDoBigAnalysisFastDelegate = new EndOperationDelegate(this.OnEndDoBigAnalysisFast);
            }
            if ((this.onDoBigAnalysisFastCompletedDelegate == null)) {
                this.onDoBigAnalysisFastCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDoBigAnalysisFastCompleted);
            }
            base.InvokeAsync(this.onBeginDoBigAnalysisFastDelegate, null, this.onEndDoBigAnalysisFastDelegate, this.onDoBigAnalysisFastCompletedDelegate, userState);
        }
        
        public void DoBigAnslysisSlow() {
            base.Channel.DoBigAnslysisSlow();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginDoBigAnslysisSlow(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDoBigAnslysisSlow(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndDoBigAnslysisSlow(System.IAsyncResult result) {
            base.Channel.EndDoBigAnslysisSlow(result);
        }
        
        private System.IAsyncResult OnBeginDoBigAnslysisSlow(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginDoBigAnslysisSlow(callback, asyncState);
        }
        
        private object[] OnEndDoBigAnslysisSlow(System.IAsyncResult result) {
            this.EndDoBigAnslysisSlow(result);
            return null;
        }
        
        private void OnDoBigAnslysisSlowCompleted(object state) {
            if ((this.DoBigAnslysisSlowCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DoBigAnslysisSlowCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DoBigAnslysisSlowAsync() {
            this.DoBigAnslysisSlowAsync(null);
        }
        
        public void DoBigAnslysisSlowAsync(object userState) {
            if ((this.onBeginDoBigAnslysisSlowDelegate == null)) {
                this.onBeginDoBigAnslysisSlowDelegate = new BeginOperationDelegate(this.OnBeginDoBigAnslysisSlow);
            }
            if ((this.onEndDoBigAnslysisSlowDelegate == null)) {
                this.onEndDoBigAnslysisSlowDelegate = new EndOperationDelegate(this.OnEndDoBigAnslysisSlow);
            }
            if ((this.onDoBigAnslysisSlowCompletedDelegate == null)) {
                this.onDoBigAnslysisSlowCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDoBigAnslysisSlowCompleted);
            }
            base.InvokeAsync(this.onBeginDoBigAnslysisSlowDelegate, null, this.onEndDoBigAnslysisSlowDelegate, this.onDoBigAnslysisSlowCompletedDelegate, userState);
        }
    }
}
