//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCYN.EF.Model
{
    using System;
    
    public partial class GetCoursesByStudentId_Result
    {
        public Nullable<int> courseid { get; set; }
        public string coursename { get; set; }
        public Nullable<int> TeacherId { get; set; }
    }
}
