<?xml version="1.0" encoding="utf-8"?><Database Name="MeetingSys" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=MeetingSys;Integrated Security=True" SettingsObjectName="XCYN.Service.Properties.Settings" SettingsPropertyName="MeetingSysConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.zcp_info" Member="zcp_info">
    <Type Name="zcp_info">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="category_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="content" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="formula_name" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="right_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="point" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="b_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="user_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="add_time" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="click" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="great_count" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="state" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="grade_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="accuracy_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>