//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCYN.EasyUI.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class zcp_SEQUENCE
    {
        public string SEQ_NAME { get; set; }
        public decimal MIN_VAL { get; set; }
        public decimal CURRENT_VAL { get; set; }
        public decimal MAX_VAL { get; set; }
        public int INCREMENT { get; set; }
    }
}
