//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCYN.Linq.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class zcp_lottery_data
    {
        public int id { get; set; }
        public string jzrq { get; set; }
        public Nullable<int> kj_qs { get; set; }
        public string kj_zm1 { get; set; }
        public string kj_zm2 { get; set; }
        public string kj_zm3 { get; set; }
        public string kj_zm4 { get; set; }
        public string kj_zm5 { get; set; }
        public string kj_zm6 { get; set; }
        public string kj_tm { get; set; }
    }
}
