//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCYN.API.Areas.Lottery.ORM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LunisolarData
    {
        public int yearId { get; set; }
        public string data { get; set; }
        public Nullable<int> dataInt { get; set; }
        public string Data1 { get; set; }
        public Nullable<int> DataInt1 { get; set; }
    }
}
