//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCYN.API.Areas.Lottery.ORM.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MeetingSysEntities : DbContext
    {
        public MeetingSysEntities()
            : base("name=MeetingSysEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<article> articles { get; set; }
        public virtual DbSet<article_albums> article_albums { get; set; }
        public virtual DbSet<article_attach> article_attach { get; set; }
        public virtual DbSet<article_attribute_field> article_attribute_field { get; set; }
        public virtual DbSet<article_attribute_value> article_attribute_value { get; set; }
        public virtual DbSet<article_category> article_category { get; set; }
        public virtual DbSet<article_comment> article_comment { get; set; }
        public virtual DbSet<channel> channels { get; set; }
        public virtual DbSet<channel_field> channel_field { get; set; }
        public virtual DbSet<channel_site> channel_site { get; set; }
        public virtual DbSet<express> expresses { get; set; }
        public virtual DbSet<feedback> feedbacks { get; set; }
        public virtual DbSet<formu_rank_config> formu_rank_config { get; set; }
        public virtual DbSet<link> links { get; set; }
        public virtual DbSet<mail_template> mail_template { get; set; }
        public virtual DbSet<manager> managers { get; set; }
        public virtual DbSet<manager_log> manager_log { get; set; }
        public virtual DbSet<manager_role> manager_role { get; set; }
        public virtual DbSet<manager_role_value> manager_role_value { get; set; }
        public virtual DbSet<navigation> navigations { get; set; }
        public virtual DbSet<order_goods> order_goods { get; set; }
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<payment> payments { get; set; }
        public virtual DbSet<point> points { get; set; }
        public virtual DbSet<role_formu_list> role_formu_list { get; set; }
        public virtual DbSet<sms_template> sms_template { get; set; }
        public virtual DbSet<system_loop_config> system_loop_config { get; set; }
        public virtual DbSet<user_amount_log> user_amount_log { get; set; }
        public virtual DbSet<user_code> user_code { get; set; }
        public virtual DbSet<user_group_price> user_group_price { get; set; }
        public virtual DbSet<user_groups> user_groups { get; set; }
        public virtual DbSet<user_login_log> user_login_log { get; set; }
        public virtual DbSet<user_message> user_message { get; set; }
        public virtual DbSet<user_oauth> user_oauth { get; set; }
        public virtual DbSet<user_oauth_app> user_oauth_app { get; set; }
        public virtual DbSet<user_point_log> user_point_log { get; set; }
        public virtual DbSet<user_recharge> user_recharge { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<zcp_ads> zcp_ads { get; set; }
        public virtual DbSet<zcp_article_post_collect> zcp_article_post_collect { get; set; }
        public virtual DbSet<zcp_article_post_great> zcp_article_post_great { get; set; }
        public virtual DbSet<zcp_auth_expert> zcp_auth_expert { get; set; }
        public virtual DbSet<zcp_auth_master> zcp_auth_master { get; set; }
        public virtual DbSet<zcp_bank> zcp_bank { get; set; }
        public virtual DbSet<zcp_bank_account> zcp_bank_account { get; set; }
        public virtual DbSet<zcp_bank_transfer> zcp_bank_transfer { get; set; }
        public virtual DbSet<zcp_bbs_cate_ext> zcp_bbs_cate_ext { get; set; }
        public virtual DbSet<zcp_bookmark> zcp_bookmark { get; set; }
        public virtual DbSet<zcp_cheap_time> zcp_cheap_time { get; set; }
        public virtual DbSet<zcp_collect_account> zcp_collect_account { get; set; }
        public virtual DbSet<zcp_database> zcp_database { get; set; }
        public virtual DbSet<zcp_exp> zcp_exp { get; set; }
        public virtual DbSet<zcp_exp_detail> zcp_exp_detail { get; set; }
        public virtual DbSet<zcp_focus> zcp_focus { get; set; }
        public virtual DbSet<zcp_form_hitrate> zcp_form_hitrate { get; set; }
        public virtual DbSet<zcp_formu_order> zcp_formu_order { get; set; }
        public virtual DbSet<zcp_formu_select_authority> zcp_formu_select_authority { get; set; }
        public virtual DbSet<zcp_formula_attr> zcp_formula_attr { get; set; }
        public virtual DbSet<zcp_formula_click> zcp_formula_click { get; set; }
        public virtual DbSet<zcp_formula_coefficient> zcp_formula_coefficient { get; set; }
        public virtual DbSet<zcp_formula_collect> zcp_formula_collect { get; set; }
        public virtual DbSet<zcp_formula_comment> zcp_formula_comment { get; set; }
        public virtual DbSet<zcp_formula_commentpraise> zcp_formula_commentpraise { get; set; }
        public virtual DbSet<zcp_formula_ext> zcp_formula_ext { get; set; }
        public virtual DbSet<zcp_formula_query_quantity> zcp_formula_query_quantity { get; set; }
        public virtual DbSet<zcp_formula_rank> zcp_formula_rank { get; set; }
        public virtual DbSet<zcp_formula_reward> zcp_formula_reward { get; set; }
        public virtual DbSet<zcp_help> zcp_help { get; set; }
        public virtual DbSet<zcp_help_cate> zcp_help_cate { get; set; }
        public virtual DbSet<zcp_info> zcp_info { get; set; }
        public virtual DbSet<zcp_info_collect> zcp_info_collect { get; set; }
        public virtual DbSet<zcp_info_detail> zcp_info_detail { get; set; }
        public virtual DbSet<zcp_info_ext> zcp_info_ext { get; set; }
        public virtual DbSet<zcp_info_small> zcp_info_small { get; set; }
        public virtual DbSet<zcp_integral_formula_category> zcp_integral_formula_category { get; set; }
        public virtual DbSet<zcp_integral_info_category> zcp_integral_info_category { get; set; }
        public virtual DbSet<zcp_invite> zcp_invite { get; set; }
        public virtual DbSet<zcp_limit_cheap> zcp_limit_cheap { get; set; }
        public virtual DbSet<zcp_lottery_data> zcp_lottery_data { get; set; }
        public virtual DbSet<zcp_lottery_record> zcp_lottery_record { get; set; }
        public virtual DbSet<zcp_mail> zcp_mail { get; set; }
        public virtual DbSet<zcp_member> zcp_member { get; set; }
        public virtual DbSet<zcp_member_exp> zcp_member_exp { get; set; }
        public virtual DbSet<zcp_member_point> zcp_member_point { get; set; }
        public virtual DbSet<zcp_member_reward> zcp_member_reward { get; set; }
        public virtual DbSet<zcp_member_right> zcp_member_right { get; set; }
        public virtual DbSet<zcp_member_signIn> zcp_member_signIn { get; set; }
        public virtual DbSet<zcp_message> zcp_message { get; set; }
        public virtual DbSet<zcp_note_bookmark> zcp_note_bookmark { get; set; }
        public virtual DbSet<zcp_notebook> zcp_notebook { get; set; }
        public virtual DbSet<zcp_operating_statement> zcp_operating_statement { get; set; }
        public virtual DbSet<zcp_order> zcp_order { get; set; }
        public virtual DbSet<zcp_para> zcp_para { get; set; }
        public virtual DbSet<zcp_picture> zcp_picture { get; set; }
        public virtual DbSet<zcp_picture_bookmark> zcp_picture_bookmark { get; set; }
        public virtual DbSet<zcp_picture_category> zcp_picture_category { get; set; }
        public virtual DbSet<zcp_picture_collect> zcp_picture_collect { get; set; }
        public virtual DbSet<zcp_picture_ext> zcp_picture_ext { get; set; }
        public virtual DbSet<zcp_picture_search> zcp_picture_search { get; set; }
        public virtual DbSet<zcp_point> zcp_point { get; set; }
        public virtual DbSet<zcp_point_log> zcp_point_log { get; set; }
        public virtual DbSet<zcp_post> zcp_post { get; set; }
        public virtual DbSet<zcp_post_collect> zcp_post_collect { get; set; }
        public virtual DbSet<zcp_post_great> zcp_post_great { get; set; }
        public virtual DbSet<zcp_post_recommend> zcp_post_recommend { get; set; }
        public virtual DbSet<zcp_rank> zcp_rank { get; set; }
        public virtual DbSet<zcp_recommend> zcp_recommend { get; set; }
        public virtual DbSet<zcp_record_bigClass> zcp_record_bigClass { get; set; }
        public virtual DbSet<zcp_record_smallClass> zcp_record_smallClass { get; set; }
        public virtual DbSet<zcp_record_yearClass> zcp_record_yearClass { get; set; }
        public virtual DbSet<zcp_reward_detail> zcp_reward_detail { get; set; }
        public virtual DbSet<zcp_signIn> zcp_signIn { get; set; }
        public virtual DbSet<zcp_space_log> zcp_space_log { get; set; }
        public virtual DbSet<zcp_superior> zcp_superior { get; set; }
        public virtual DbSet<zcp_test> zcp_test { get; set; }
        public virtual DbSet<zcp_third_account> zcp_third_account { get; set; }
        public virtual DbSet<zcp_third_party> zcp_third_party { get; set; }
        public virtual DbSet<zcp_third_transfer> zcp_third_transfer { get; set; }
        public virtual DbSet<zcp_users> zcp_users { get; set; }
        public virtual DbSet<zcp_users_vip> zcp_users_vip { get; set; }
        public virtual DbSet<zcp_vote_option> zcp_vote_option { get; set; }
        public virtual DbSet<zcp_vote_record> zcp_vote_record { get; set; }
        public virtual DbSet<zcp_vote_type> zcp_vote_type { get; set; }
        public virtual DbSet<attr_param_table> attr_param_table { get; set; }
        public virtual DbSet<attr_table_by_year> attr_table_by_year { get; set; }
        public virtual DbSet<ballnum_attrValue_map> ballnum_attrValue_map { get; set; }
        public virtual DbSet<duplic_param_table> duplic_param_table { get; set; }
        public virtual DbSet<formu_lichun_date> formu_lichun_date { get; set; }
        public virtual DbSet<Gregorian_lunar_map> Gregorian_lunar_map { get; set; }
        public virtual DbSet<LunisolarData> LunisolarDatas { get; set; }
        public virtual DbSet<LunisolarSolarTerm> LunisolarSolarTerms { get; set; }
        public virtual DbSet<original_formula_hito> original_formula_hito { get; set; }
        public virtual DbSet<solardata> solardatas { get; set; }
        public virtual DbSet<user_attach_log> user_attach_log { get; set; }
        public virtual DbSet<whan_ball_attr_table> whan_ball_attr_table { get; set; }
        public virtual DbSet<zcp_attr_param_table> zcp_attr_param_table { get; set; }
        public virtual DbSet<zcp_attr_param_table_bak> zcp_attr_param_table_bak { get; set; }
        public virtual DbSet<zcp_attr_param_table2> zcp_attr_param_table2 { get; set; }
        public virtual DbSet<zcp_attr_relation_table> zcp_attr_relation_table { get; set; }
        public virtual DbSet<zcp_ballnum_attrValue_map> zcp_ballnum_attrValue_map { get; set; }
        public virtual DbSet<zcp_bank_withdrawal> zcp_bank_withdrawal { get; set; }
        public virtual DbSet<zcp_combin_formula_list> zcp_combin_formula_list { get; set; }
        public virtual DbSet<zcp_comment> zcp_comment { get; set; }
        public virtual DbSet<zcp_direction> zcp_direction { get; set; }
        public virtual DbSet<zcp_formula> zcp_formula { get; set; }
        public virtual DbSet<zcp_formula_accuracy> zcp_formula_accuracy { get; set; }
        public virtual DbSet<zcp_formula_bookmark> zcp_formula_bookmark { get; set; }
        public virtual DbSet<zcp_formula_category> zcp_formula_category { get; set; }
        public virtual DbSet<zcp_formula_list> zcp_formula_list { get; set; }
        public virtual DbSet<zcp_formula_list2> zcp_formula_list2 { get; set; }
        public virtual DbSet<zcp_formula_point> zcp_formula_point { get; set; }
        public virtual DbSet<zcp_formula_praise> zcp_formula_praise { get; set; }
        public virtual DbSet<zcp_formula_small> zcp_formula_small { get; set; }
        public virtual DbSet<zcp_info_accuracy> zcp_info_accuracy { get; set; }
        public virtual DbSet<zcp_info_bak> zcp_info_bak { get; set; }
        public virtual DbSet<zcp_info_bookmark> zcp_info_bookmark { get; set; }
        public virtual DbSet<zcp_info_category> zcp_info_category { get; set; }
        public virtual DbSet<zcp_info_click> zcp_info_click { get; set; }
        public virtual DbSet<zcp_info_coefficient> zcp_info_coefficient { get; set; }
        public virtual DbSet<zcp_info_comment> zcp_info_comment { get; set; }
        public virtual DbSet<zcp_info_commentpraise> zcp_info_commentpraise { get; set; }
        public virtual DbSet<zcp_info_hitrate> zcp_info_hitrate { get; set; }
        public virtual DbSet<zcp_info_order> zcp_info_order { get; set; }
        public virtual DbSet<zcp_info_point> zcp_info_point { get; set; }
        public virtual DbSet<zcp_info_praise> zcp_info_praise { get; set; }
        public virtual DbSet<zcp_info_rank> zcp_info_rank { get; set; }
        public virtual DbSet<zcp_info_reward> zcp_info_reward { get; set; }
        public virtual DbSet<zcp_lottery_bak> zcp_lottery_bak { get; set; }
        public virtual DbSet<zcp_SEQUENCE> zcp_SEQUENCE { get; set; }
        public virtual DbSet<zcp_sx_table> zcp_sx_table { get; set; }
        public virtual DbSet<zcp_whan_attr_table> zcp_whan_attr_table { get; set; }
        public virtual DbSet<ballnum_attrValue_map_view> ballnum_attrValue_map_view { get; set; }
        public virtual DbSet<v_collect> v_collect { get; set; }
        public virtual DbSet<v_collect_account> v_collect_account { get; set; }
        public virtual DbSet<v_collect_count> v_collect_count { get; set; }
        public virtual DbSet<v_focus> v_focus { get; set; }
        public virtual DbSet<v_formu_info_post> v_formu_info_post { get; set; }
        public virtual DbSet<v_formula_ext> v_formula_ext { get; set; }
        public virtual DbSet<v_get_exp_rank_tb> v_get_exp_rank_tb { get; set; }
        public virtual DbSet<v_invit> v_invit { get; set; }
        public virtual DbSet<v_last_lottery> v_last_lottery { get; set; }
        public virtual DbSet<v_limit_formula> v_limit_formula { get; set; }
        public virtual DbSet<v_limit_info> v_limit_info { get; set; }
        public virtual DbSet<v_my_comment> v_my_comment { get; set; }
        public virtual DbSet<v_orig_formula> v_orig_formula { get; set; }
        public virtual DbSet<v_picture> v_picture { get; set; }
        public virtual DbSet<v_post_expert> v_post_expert { get; set; }
        public virtual DbSet<v_post_list> v_post_list { get; set; }
        public virtual DbSet<v_recommend> v_recommend { get; set; }
        public virtual DbSet<v_shop_all> v_shop_all { get; set; }
        public virtual DbSet<v_space_log> v_space_log { get; set; }
        public virtual DbSet<v_ta_formula> v_ta_formula { get; set; }
        public virtual DbSet<v_users_ext> v_users_ext { get; set; }
        public virtual DbSet<v_vote_record> v_vote_record { get; set; }
        public virtual DbSet<view_channel_bbs> view_channel_bbs { get; set; }
        public virtual DbSet<view_channel_kj_info> view_channel_kj_info { get; set; }
        public virtual DbSet<view_formula_mode> view_formula_mode { get; set; }
        public virtual DbSet<view_role> view_role { get; set; }
        public virtual DbSet<view_select_param> view_select_param { get; set; }
        public virtual DbSet<view_zcp_order> view_zcp_order { get; set; }
    
        [DbFunction("MeetingSysEntities", "f_LunisolarYearDays")]
        public virtual IQueryable<f_LunisolarYearDays_Result> f_LunisolarYearDays(string year)
        {
            var yearParameter = year != null ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_LunisolarYearDays_Result>("[MeetingSysEntities].[f_LunisolarYearDays](@Year)", yearParameter);
        }
    
        [DbFunction("MeetingSysEntities", "f_select_value")]
        public virtual IQueryable<f_select_value_Result> f_select_value(string gs_name, string selectBalls)
        {
            var gs_nameParameter = gs_name != null ?
                new ObjectParameter("gs_name", gs_name) :
                new ObjectParameter("gs_name", typeof(string));
    
            var selectBallsParameter = selectBalls != null ?
                new ObjectParameter("selectBalls", selectBalls) :
                new ObjectParameter("selectBalls", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_select_value_Result>("[MeetingSysEntities].[f_select_value](@gs_name, @selectBalls)", gs_nameParameter, selectBallsParameter);
        }
    
        [DbFunction("MeetingSysEntities", "f_splitSTR")]
        public virtual IQueryable<f_splitSTR_Result> f_splitSTR(string s, string split)
        {
            var sParameter = s != null ?
                new ObjectParameter("s", s) :
                new ObjectParameter("s", typeof(string));
    
            var splitParameter = split != null ?
                new ObjectParameter("split", split) :
                new ObjectParameter("split", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_splitSTR_Result>("[MeetingSysEntities].[f_splitSTR](@s, @split)", sParameter, splitParameter);
        }
    
        [DbFunction("MeetingSysEntities", "get_yushu_relation")]
        public virtual IQueryable<get_yushu_relation_Result> get_yushu_relation(Nullable<int> mod)
        {
            var modParameter = mod.HasValue ?
                new ObjectParameter("mod", mod) :
                new ObjectParameter("mod", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<get_yushu_relation_Result>("[MeetingSysEntities].[get_yushu_relation](@mod)", modParameter);
        }
    
        public virtual int append_param_value(string sBallDirSet, string paramlist, string sBegin_jzrq, string sEnd_jzrq, Nullable<int> iballOrder)
        {
            var sBallDirSetParameter = sBallDirSet != null ?
                new ObjectParameter("sBallDirSet", sBallDirSet) :
                new ObjectParameter("sBallDirSet", typeof(string));
    
            var paramlistParameter = paramlist != null ?
                new ObjectParameter("paramlist", paramlist) :
                new ObjectParameter("paramlist", typeof(string));
    
            var sBegin_jzrqParameter = sBegin_jzrq != null ?
                new ObjectParameter("sBegin_jzrq", sBegin_jzrq) :
                new ObjectParameter("sBegin_jzrq", typeof(string));
    
            var sEnd_jzrqParameter = sEnd_jzrq != null ?
                new ObjectParameter("sEnd_jzrq", sEnd_jzrq) :
                new ObjectParameter("sEnd_jzrq", typeof(string));
    
            var iballOrderParameter = iballOrder.HasValue ?
                new ObjectParameter("iballOrder", iballOrder) :
                new ObjectParameter("iballOrder", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("append_param_value", sBallDirSetParameter, paramlistParameter, sBegin_jzrqParameter, sEnd_jzrqParameter, iballOrderParameter);
        }
    
        public virtual int append_param_value_bak(string sBallDirSet, string paramlist, string sBegin_jzrq, string sEnd_jzrq, Nullable<int> iballOrder)
        {
            var sBallDirSetParameter = sBallDirSet != null ?
                new ObjectParameter("sBallDirSet", sBallDirSet) :
                new ObjectParameter("sBallDirSet", typeof(string));
    
            var paramlistParameter = paramlist != null ?
                new ObjectParameter("paramlist", paramlist) :
                new ObjectParameter("paramlist", typeof(string));
    
            var sBegin_jzrqParameter = sBegin_jzrq != null ?
                new ObjectParameter("sBegin_jzrq", sBegin_jzrq) :
                new ObjectParameter("sBegin_jzrq", typeof(string));
    
            var sEnd_jzrqParameter = sEnd_jzrq != null ?
                new ObjectParameter("sEnd_jzrq", sEnd_jzrq) :
                new ObjectParameter("sEnd_jzrq", typeof(string));
    
            var iballOrderParameter = iballOrder.HasValue ?
                new ObjectParameter("iballOrder", iballOrder) :
                new ObjectParameter("iballOrder", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("append_param_value_bak", sBallDirSetParameter, paramlistParameter, sBegin_jzrqParameter, sEnd_jzrqParameter, iballOrderParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> article_hot_danshuang(string kj_nf, Nullable<int> danshuang)
        {
            var kj_nfParameter = kj_nf != null ?
                new ObjectParameter("kj_nf", kj_nf) :
                new ObjectParameter("kj_nf", typeof(string));
    
            var danshuangParameter = danshuang.HasValue ?
                new ObjectParameter("danshuang", danshuang) :
                new ObjectParameter("danshuang", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("article_hot_danshuang", kj_nfParameter, danshuangParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> article_hot_daxiao(string kj_nf, Nullable<int> daxiao)
        {
            var kj_nfParameter = kj_nf != null ?
                new ObjectParameter("kj_nf", kj_nf) :
                new ObjectParameter("kj_nf", typeof(string));
    
            var daxiaoParameter = daxiao.HasValue ?
                new ObjectParameter("daxiao", daxiao) :
                new ObjectParameter("daxiao", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("article_hot_daxiao", kj_nfParameter, daxiaoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> article_hot_number(string kj_nf, string number)
        {
            var kj_nfParameter = kj_nf != null ?
                new ObjectParameter("kj_nf", kj_nf) :
                new ObjectParameter("kj_nf", typeof(string));
    
            var numberParameter = number != null ?
                new ObjectParameter("number", number) :
                new ObjectParameter("number", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("article_hot_number", kj_nfParameter, numberParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> article_hot_number_tm(string kj_nf, string number)
        {
            var kj_nfParameter = kj_nf != null ?
                new ObjectParameter("kj_nf", kj_nf) :
                new ObjectParameter("kj_nf", typeof(string));
    
            var numberParameter = number != null ?
                new ObjectParameter("number", number) :
                new ObjectParameter("number", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("article_hot_number_tm", kj_nfParameter, numberParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> article_hot_shengxiao(string kj_nf, string last_year_sx, string this_year_sx, Nullable<System.DateTime> nl_date)
        {
            var kj_nfParameter = kj_nf != null ?
                new ObjectParameter("kj_nf", kj_nf) :
                new ObjectParameter("kj_nf", typeof(string));
    
            var last_year_sxParameter = last_year_sx != null ?
                new ObjectParameter("last_year_sx", last_year_sx) :
                new ObjectParameter("last_year_sx", typeof(string));
    
            var this_year_sxParameter = this_year_sx != null ?
                new ObjectParameter("this_year_sx", this_year_sx) :
                new ObjectParameter("this_year_sx", typeof(string));
    
            var nl_dateParameter = nl_date.HasValue ?
                new ObjectParameter("nl_date", nl_date) :
                new ObjectParameter("nl_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("article_hot_shengxiao", kj_nfParameter, last_year_sxParameter, this_year_sxParameter, nl_dateParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> article_yilou_danshuang(string kj_nf, Nullable<int> danshuang)
        {
            var kj_nfParameter = kj_nf != null ?
                new ObjectParameter("kj_nf", kj_nf) :
                new ObjectParameter("kj_nf", typeof(string));
    
            var danshuangParameter = danshuang.HasValue ?
                new ObjectParameter("danshuang", danshuang) :
                new ObjectParameter("danshuang", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("article_yilou_danshuang", kj_nfParameter, danshuangParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> article_yilou_daxiao(string kj_nf, Nullable<int> daxiao)
        {
            var kj_nfParameter = kj_nf != null ?
                new ObjectParameter("kj_nf", kj_nf) :
                new ObjectParameter("kj_nf", typeof(string));
    
            var daxiaoParameter = daxiao.HasValue ?
                new ObjectParameter("daxiao", daxiao) :
                new ObjectParameter("daxiao", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("article_yilou_daxiao", kj_nfParameter, daxiaoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> article_yilou_qs(string kj_nf, string number)
        {
            var kj_nfParameter = kj_nf != null ?
                new ObjectParameter("kj_nf", kj_nf) :
                new ObjectParameter("kj_nf", typeof(string));
    
            var numberParameter = number != null ?
                new ObjectParameter("number", number) :
                new ObjectParameter("number", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("article_yilou_qs", kj_nfParameter, numberParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> article_yilou_qs_tm(string kj_nf, string number)
        {
            var kj_nfParameter = kj_nf != null ?
                new ObjectParameter("kj_nf", kj_nf) :
                new ObjectParameter("kj_nf", typeof(string));
    
            var numberParameter = number != null ?
                new ObjectParameter("number", number) :
                new ObjectParameter("number", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("article_yilou_qs_tm", kj_nfParameter, numberParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> article_yilou_shengxiao(string kj_nf, string last_year_sx, string this_year_sx, Nullable<System.DateTime> nl_date)
        {
            var kj_nfParameter = kj_nf != null ?
                new ObjectParameter("kj_nf", kj_nf) :
                new ObjectParameter("kj_nf", typeof(string));
    
            var last_year_sxParameter = last_year_sx != null ?
                new ObjectParameter("last_year_sx", last_year_sx) :
                new ObjectParameter("last_year_sx", typeof(string));
    
            var this_year_sxParameter = this_year_sx != null ?
                new ObjectParameter("this_year_sx", this_year_sx) :
                new ObjectParameter("this_year_sx", typeof(string));
    
            var nl_dateParameter = nl_date.HasValue ?
                new ObjectParameter("nl_date", nl_date) :
                new ObjectParameter("nl_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("article_yilou_shengxiao", kj_nfParameter, last_year_sxParameter, this_year_sxParameter, nl_dateParameter);
        }
    
        public virtual int calc_formu_hitrate(string sBallDirSet, string paramlist, Nullable<int> iballOrder)
        {
            var sBallDirSetParameter = sBallDirSet != null ?
                new ObjectParameter("sBallDirSet", sBallDirSet) :
                new ObjectParameter("sBallDirSet", typeof(string));
    
            var paramlistParameter = paramlist != null ?
                new ObjectParameter("paramlist", paramlist) :
                new ObjectParameter("paramlist", typeof(string));
    
            var iballOrderParameter = iballOrder.HasValue ?
                new ObjectParameter("iballOrder", iballOrder) :
                new ObjectParameter("iballOrder", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("calc_formu_hitrate", sBallDirSetParameter, paramlistParameter, iballOrderParameter);
        }
    
        public virtual ObjectResult<calc_latest_ranking_Result> calc_latest_ranking(Nullable<int> type)
        {
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<calc_latest_ranking_Result>("calc_latest_ranking", typeParameter);
        }
    
        public virtual int calc_param_value(string sBallDirSet, string paramlist, string sBegin_Yearqs, string sEnd_Yearqs, Nullable<int> iballOrder, Nullable<int> formu_type)
        {
            var sBallDirSetParameter = sBallDirSet != null ?
                new ObjectParameter("sBallDirSet", sBallDirSet) :
                new ObjectParameter("sBallDirSet", typeof(string));
    
            var paramlistParameter = paramlist != null ?
                new ObjectParameter("paramlist", paramlist) :
                new ObjectParameter("paramlist", typeof(string));
    
            var sBegin_YearqsParameter = sBegin_Yearqs != null ?
                new ObjectParameter("sBegin_Yearqs", sBegin_Yearqs) :
                new ObjectParameter("sBegin_Yearqs", typeof(string));
    
            var sEnd_YearqsParameter = sEnd_Yearqs != null ?
                new ObjectParameter("sEnd_Yearqs", sEnd_Yearqs) :
                new ObjectParameter("sEnd_Yearqs", typeof(string));
    
            var iballOrderParameter = iballOrder.HasValue ?
                new ObjectParameter("iballOrder", iballOrder) :
                new ObjectParameter("iballOrder", typeof(int));
    
            var formu_typeParameter = formu_type.HasValue ?
                new ObjectParameter("formu_type", formu_type) :
                new ObjectParameter("formu_type", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("calc_param_value", sBallDirSetParameter, paramlistParameter, sBegin_YearqsParameter, sEnd_YearqsParameter, iballOrderParameter, formu_typeParameter);
        }
    
        public virtual int calc_users_interRate(Nullable<int> type, Nullable<int> user_id)
        {
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(int));
    
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("calc_users_interRate", typeParameter, user_idParameter);
        }
    
        public virtual ObjectResult<formulaOrigina_Result> formulaOrigina()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<formulaOrigina_Result>("formulaOrigina");
        }
    
        public virtual ObjectResult<get_formulaset_by_roleid_Result> get_formulaset_by_roleid(Nullable<int> roleid)
        {
            var roleidParameter = roleid.HasValue ?
                new ObjectParameter("roleid", roleid) :
                new ObjectParameter("roleid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_formulaset_by_roleid_Result>("get_formulaset_by_roleid", roleidParameter);
        }
    
        public virtual ObjectResult<gs_original_Billboard_Result> gs_original_Billboard(Nullable<int> type)
        {
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<gs_original_Billboard_Result>("gs_original_Billboard", typeParameter);
        }
    
        public virtual int info_order_add(Nullable<int> info_id, string order_no, Nullable<int> user_id, Nullable<int> point)
        {
            var info_idParameter = info_id.HasValue ?
                new ObjectParameter("info_id", info_id) :
                new ObjectParameter("info_id", typeof(int));
    
            var order_noParameter = order_no != null ?
                new ObjectParameter("order_no", order_no) :
                new ObjectParameter("order_no", typeof(string));
    
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            var pointParameter = point.HasValue ?
                new ObjectParameter("point", point) :
                new ObjectParameter("point", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("info_order_add", info_idParameter, order_noParameter, user_idParameter, pointParameter);
        }
    
        public virtual int info_original_Billboard(Nullable<int> type)
        {
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("info_original_Billboard", typeParameter);
        }
    
        public virtual ObjectResult<infoOrigina_Result> infoOrigina()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<infoOrigina_Result>("infoOrigina");
        }
    
        public virtual int load_param_value(string sBallDirSet, string paramlist, Nullable<int> qsnums, string sEnd_Yearqs, Nullable<int> iballOrder)
        {
            var sBallDirSetParameter = sBallDirSet != null ?
                new ObjectParameter("sBallDirSet", sBallDirSet) :
                new ObjectParameter("sBallDirSet", typeof(string));
    
            var paramlistParameter = paramlist != null ?
                new ObjectParameter("paramlist", paramlist) :
                new ObjectParameter("paramlist", typeof(string));
    
            var qsnumsParameter = qsnums.HasValue ?
                new ObjectParameter("qsnums", qsnums) :
                new ObjectParameter("qsnums", typeof(int));
    
            var sEnd_YearqsParameter = sEnd_Yearqs != null ?
                new ObjectParameter("sEnd_Yearqs", sEnd_Yearqs) :
                new ObjectParameter("sEnd_Yearqs", typeof(string));
    
            var iballOrderParameter = iballOrder.HasValue ?
                new ObjectParameter("iballOrder", iballOrder) :
                new ObjectParameter("iballOrder", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("load_param_value", sBallDirSetParameter, paramlistParameter, qsnumsParameter, sEnd_YearqsParameter, iballOrderParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> order_add(Nullable<int> formula_id, string order_no, Nullable<int> user_id, Nullable<int> point)
        {
            var formula_idParameter = formula_id.HasValue ?
                new ObjectParameter("formula_id", formula_id) :
                new ObjectParameter("formula_id", typeof(int));
    
            var order_noParameter = order_no != null ?
                new ObjectParameter("order_no", order_no) :
                new ObjectParameter("order_no", typeof(string));
    
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            var pointParameter = point.HasValue ?
                new ObjectParameter("point", point) :
                new ObjectParameter("point", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("order_add", formula_idParameter, order_noParameter, user_idParameter, pointParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> order_user_add(Nullable<int> owner_id, string order_no, Nullable<int> user_id, Nullable<int> point)
        {
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var order_noParameter = order_no != null ?
                new ObjectParameter("order_no", order_no) :
                new ObjectParameter("order_no", typeof(string));
    
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            var pointParameter = point.HasValue ?
                new ObjectParameter("point", point) :
                new ObjectParameter("point", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("order_user_add", owner_idParameter, order_noParameter, user_idParameter, pointParameter);
        }
    
        public virtual int p_formu_fresh_rank(Nullable<int> iFormu_info_type)
        {
            var iFormu_info_typeParameter = iFormu_info_type.HasValue ?
                new ObjectParameter("iFormu_info_type", iFormu_info_type) :
                new ObjectParameter("iFormu_info_type", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_formu_fresh_rank", iFormu_info_typeParameter);
        }
    
        public virtual int p_formu_fresh_rank_bak(Nullable<int> iFormu_info_type)
        {
            var iFormu_info_typeParameter = iFormu_info_type.HasValue ?
                new ObjectParameter("iFormu_info_type", iFormu_info_type) :
                new ObjectParameter("iFormu_info_type", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_formu_fresh_rank_bak", iFormu_info_typeParameter);
        }
    
        public virtual int p_fresh_rank(Nullable<int> iFormu_info_type)
        {
            var iFormu_info_typeParameter = iFormu_info_type.HasValue ?
                new ObjectParameter("iFormu_info_type", iFormu_info_type) :
                new ObjectParameter("iFormu_info_type", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_fresh_rank", iFormu_info_typeParameter);
        }
    
        public virtual int p_info_fresh_rank(Nullable<int> iFormu_info_type)
        {
            var iFormu_info_typeParameter = iFormu_info_type.HasValue ?
                new ObjectParameter("iFormu_info_type", iFormu_info_type) :
                new ObjectParameter("iFormu_info_type", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_info_fresh_rank", iFormu_info_typeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> review_recharge(Nullable<int> t_id)
        {
            var t_idParameter = t_id.HasValue ?
                new ObjectParameter("t_id", t_id) :
                new ObjectParameter("t_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("review_recharge", t_idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> review_withdrawal(Nullable<int> t_id)
        {
            var t_idParameter = t_id.HasValue ?
                new ObjectParameter("t_id", t_id) :
                new ObjectParameter("t_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("review_withdrawal", t_idParameter);
        }
    
        public virtual int setFormulaRole(Nullable<int> roleid, string data)
        {
            var roleidParameter = roleid.HasValue ?
                new ObjectParameter("roleid", roleid) :
                new ObjectParameter("roleid", typeof(int));
    
            var dataParameter = data != null ?
                new ObjectParameter("data", data) :
                new ObjectParameter("data", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("setFormulaRole", roleidParameter, dataParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> thirdReview_recharge(Nullable<int> t_id)
        {
            var t_idParameter = t_id.HasValue ?
                new ObjectParameter("t_id", t_id) :
                new ObjectParameter("t_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("thirdReview_recharge", t_idParameter);
        }
    
        public virtual int UP_Paging2015(string tableName, string fields, string orderField, Nullable<int> pageSize, Nullable<int> pageIndex, string sqlWhere, ObjectParameter totalRecord)
        {
            var tableNameParameter = tableName != null ?
                new ObjectParameter("TableName", tableName) :
                new ObjectParameter("TableName", typeof(string));
    
            var fieldsParameter = fields != null ?
                new ObjectParameter("Fields", fields) :
                new ObjectParameter("Fields", typeof(string));
    
            var orderFieldParameter = orderField != null ?
                new ObjectParameter("OrderField", orderField) :
                new ObjectParameter("OrderField", typeof(string));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("pageSize", pageSize) :
                new ObjectParameter("pageSize", typeof(int));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("pageIndex", pageIndex) :
                new ObjectParameter("pageIndex", typeof(int));
    
            var sqlWhereParameter = sqlWhere != null ?
                new ObjectParameter("sqlWhere", sqlWhere) :
                new ObjectParameter("sqlWhere", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UP_Paging2015", tableNameParameter, fieldsParameter, orderFieldParameter, pageSizeParameter, pageIndexParameter, sqlWhereParameter, totalRecord);
        }
    
        public virtual int userGetExp(string action, Nullable<int> user_id)
        {
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("userGetExp", actionParameter, user_idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> userReleasePoint(Nullable<int> user_id)
        {
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("userReleasePoint", user_idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> userReward(Nullable<int> user_id)
        {
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("userReward", user_idParameter);
        }
    }
}
