//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCYN.API.Areas.Lottery.ORM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class navigation
    {
        public int id { get; set; }
        public Nullable<int> parent_id { get; set; }
        public Nullable<int> channel_id { get; set; }
        public string nav_type { get; set; }
        public string name { get; set; }
        public string title { get; set; }
        public string sub_title { get; set; }
        public string icon_url { get; set; }
        public string link_url { get; set; }
        public Nullable<int> sort_id { get; set; }
        public Nullable<byte> is_lock { get; set; }
        public string remark { get; set; }
        public string action_type { get; set; }
        public Nullable<byte> is_sys { get; set; }
    }
}
