//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCYN.API.Areas.Lottery.ORM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_goods
    {
        public int id { get; set; }
        public Nullable<int> article_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public string goods_no { get; set; }
        public string goods_title { get; set; }
        public string img_url { get; set; }
        public string spec_text { get; set; }
        public Nullable<decimal> goods_price { get; set; }
        public Nullable<decimal> real_price { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> point { get; set; }
    
        public virtual order order { get; set; }
    }
}
