//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCYN.API.Areas.Lottery.ORM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_template
    {
        public int id { get; set; }
        public string title { get; set; }
        public string call_index { get; set; }
        public string content { get; set; }
        public Nullable<byte> is_sys { get; set; }
    }
}
