//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCYN.API.Areas.Lottery.ORM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_get_exp_rank_tb
    {
        public string action { get; set; }
        public string rank { get; set; }
        public Nullable<int> exper { get; set; }
        public int exp_id { get; set; }
        public Nullable<int> member_id { get; set; }
    }
}
