//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCYN.API.Areas.Lottery.ORM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_limit_formula
    {
        public int id { get; set; }
        public int category_id { get; set; }
        public string formula_name { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<bool> formula_home { get; set; }
        public Nullable<bool> hot_special { get; set; }
        public Nullable<bool> last_formula { get; set; }
        public Nullable<bool> special_formula { get; set; }
        public Nullable<bool> today_special { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<int> right_id { get; set; }
        public Nullable<int> accuracy_id { get; set; }
        public Nullable<int> grade_id { get; set; }
        public Nullable<int> special_time { get; set; }
        public Nullable<System.DateTime> add_time { get; set; }
        public Nullable<int> point { get; set; }
        public Nullable<int> special_point { get; set; }
    }
}
