//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCYN.API.Areas.Lottery.ORM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_post_expert
    {
        public int id { get; set; }
        public int channel_id { get; set; }
        public int category_id { get; set; }
        public string title { get; set; }
        public string zhaiyao { get; set; }
        public string content { get; set; }
        public Nullable<int> click { get; set; }
        public Nullable<byte> status { get; set; }
        public string user_name { get; set; }
        public Nullable<System.DateTime> add_time { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public Nullable<bool> is_dailyHot { get; set; }
        public Nullable<System.DateTime> dailyHot_time { get; set; }
        public Nullable<bool> is_hotTopic { get; set; }
        public Nullable<System.DateTime> hotTopic_time { get; set; }
        public Nullable<bool> is_popularHot { get; set; }
        public Nullable<System.DateTime> popularHot_time { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> point { get; set; }
        public Nullable<int> collect_count { get; set; }
        public Nullable<int> great_count { get; set; }
        public Nullable<int> Expr1 { get; set; }
        public Nullable<int> group_id { get; set; }
        public string Expr2 { get; set; }
        public string salt { get; set; }
        public string password { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string avatar { get; set; }
        public string nick_name { get; set; }
        public string sex { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string telphone { get; set; }
        public string area { get; set; }
        public string address { get; set; }
        public string qq { get; set; }
        public string msn { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<int> Expr6 { get; set; }
        public Nullable<int> exp { get; set; }
        public Nullable<byte> Expr3 { get; set; }
        public Nullable<System.DateTime> reg_time { get; set; }
        public string reg_ip { get; set; }
        public Nullable<int> Expr4 { get; set; }
        public Nullable<int> Expr5 { get; set; }
        public string login_ip { get; set; }
        public Nullable<System.DateTime> login_time { get; set; }
        public string last_login_ip { get; set; }
        public Nullable<System.DateTime> last_login_time { get; set; }
        public string message { get; set; }
        public Nullable<int> is_expert { get; set; }
        public Nullable<int> online_state { get; set; }
        public Nullable<System.DateTime> active_time { get; set; }
    }
}
