//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCYN.API.Areas.Lottery.ORM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_formula_mode
    {
        public string dirset { get; set; }
        public string six_name { get; set; }
        public string gs_name { get; set; }
        public int hit_type { get; set; }
        public int calc_type { get; set; }
        public string LR_scope { get; set; }
    }
}
