//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCYN.API.Areas.Lottery.ORM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class zcp_formula
    {
        public int id { get; set; }
        public int category_id { get; set; }
        public string content { get; set; }
        public string formula_info { get; set; }
        public string formula_name { get; set; }
        public Nullable<int> right_id { get; set; }
        public Nullable<int> point { get; set; }
        public Nullable<int> b_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<System.DateTime> add_time { get; set; }
        public Nullable<int> click { get; set; }
        public Nullable<int> great_count { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<int> grade_id { get; set; }
        public Nullable<int> accuracy_id { get; set; }
        public Nullable<int> special_point { get; set; }
        public Nullable<int> special_time { get; set; }
        public string gs_name { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public Nullable<int> iballOrder { get; set; }
        public string sBallDirSet { get; set; }
        public Nullable<int> iCalc_type { get; set; }
        public Nullable<int> iHitType { get; set; }
        public string LR_SCOPE { get; set; }
        public Nullable<int> isSix_gs { get; set; }
        public string jzrq { get; set; }
        public Nullable<int> cur_times { get; set; }
        public Nullable<int> collect_count { get; set; }
        public string start_time_qs { get; set; }
        public string end_time_qs { get; set; }
        public Nullable<int> Pushingformula { get; set; }
        public Nullable<int> is_hot { get; set; }
        public Nullable<int> is_vip { get; set; }
        public Nullable<bool> is_totalclick { get; set; }
        public Nullable<bool> is_weekclick { get; set; }
        public Nullable<bool> is_dayclick { get; set; }
    }
}
