//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCYN.API.Areas.Lottery.ORM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class zcp_sx_table
    {
        public string sxname { get; set; }
        public string sx_exp { get; set; }
        public Nullable<short> sx_value { get; set; }
        public string cor_num_str { get; set; }
    }
}
