//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCYN.API.Areas.Lottery.ORM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class zcp_info_ext
    {
        public int id { get; set; }
        public int info_id { get; set; }
        public string hitinfo { get; set; }
        public string dcinfo { get; set; }
        public Nullable<int> vip_push { get; set; }
        public Nullable<int> viphot { get; set; }
        public Nullable<int> is_master { get; set; }
        public Nullable<System.DateTime> totalclick_date { get; set; }
        public Nullable<System.DateTime> weekclick_date { get; set; }
        public Nullable<System.DateTime> dayclick_date { get; set; }
    }
}
