//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCYN.API.Areas.Lottery.ORM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class zcp_picture
    {
        public int id { get; set; }
        public string name { get; set; }
        public string source { get; set; }
        public string intro { get; set; }
        public Nullable<int> category_id { get; set; }
        public string author { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> qs { get; set; }
        public string path { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<System.DateTime> add_time { get; set; }
    }
}
