//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCYN.API.Areas.Lottery.ORM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class zcp_database
    {
        public int id { get; set; }
        public string d_code { get; set; }
        public string d_zodiac { get; set; }
        public string d_five_elements { get; set; }
        public string d_poultry { get; set; }
        public string d_sex_zodiac { get; set; }
        public string d_world_zodiac { get; set; }
        public string d_year_zodiac { get; set; }
        public string d_jiayu_zodiac { get; set; }
        public string d_colour_zodiac { get; set; }
    }
}
