//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCYN.API.Areas.Lottery.ORM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class zcp_bank_transfer
    {
        public int id { get; set; }
        public Nullable<int> a_id { get; set; }
        public string bank_name { get; set; }
        public string sender { get; set; }
        public Nullable<decimal> money { get; set; }
        public string currency { get; set; }
        public Nullable<System.DateTime> transfer_time { get; set; }
        public string number { get; set; }
        public string remark { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<System.DateTime> add_time { get; set; }
        public Nullable<System.DateTime> review_time { get; set; }
        public Nullable<int> user_id { get; set; }
    }
}
