//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCYN.API.Areas.Lottery.ORM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class zcp_picture_ext
    {
        public int id { get; set; }
        public Nullable<int> c_id { get; set; }
        public Nullable<bool> is_hot { get; set; }
        public Nullable<bool> is_hotclick { get; set; }
        public Nullable<int> hotclick_rank { get; set; }
        public Nullable<bool> is_exec { get; set; }
        public Nullable<bool> is_popu { get; set; }
        public Nullable<int> popu_rank { get; set; }
        public Nullable<bool> is_vip { get; set; }
        public Nullable<bool> is_vipclick { get; set; }
        public Nullable<int> vipclick_rank { get; set; }
        public Nullable<bool> is_last { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<System.DateTime> add_time { get; set; }
    }
}
