//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCYN.API.Areas.Lottery.ORM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class zcp_info_detail
    {
        public int id { get; set; }
        public Nullable<int> p_id { get; set; }
        public int category_id { get; set; }
        public string formula_info { get; set; }
        public Nullable<int> grade_id { get; set; }
        public string gs_name { get; set; }
        public Nullable<int> iballOrder { get; set; }
        public string sBallDirSet { get; set; }
        public Nullable<int> iCalc_type { get; set; }
        public Nullable<int> iHitType { get; set; }
        public string LR_SCOPE { get; set; }
        public Nullable<int> isSix_gs { get; set; }
        public string jzrq { get; set; }
        public Nullable<int> cur_times { get; set; }
    }
}
