//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCYN.EasyUI.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_last_lottery
    {
        public int id { get; set; }
        public string year { get; set; }
        public string periods { get; set; }
        public string formal_number { get; set; }
        public string special_number { get; set; }
        public Nullable<System.DateTime> add_time { get; set; }
        public Nullable<System.DateTime> lottery_time { get; set; }
        public Nullable<int> state { get; set; }
    }
}
