//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCYN.Knockout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_detail
    {
        public int id { get; set; }
        public Nullable<int> p_id { get; set; }
        public Nullable<int> amount { get; set; }
        public Nullable<bool> state { get; set; }
        public Nullable<System.DateTimeOffset> add_time { get; set; }
        public Nullable<int> product_id { get; set; }
    }
}
