//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCYN.Winform.Model.MeiTuan.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MeiTuanEntities : DbContext
    {
        public MeiTuanEntities()
            : base("name=MeiTuanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_Areas> T_Areas { get; set; }
        public virtual DbSet<T_Cate> T_Cate { get; set; }
        public virtual DbSet<T_City> T_City { get; set; }
        public virtual DbSet<T_DinnerCountsAttr> T_DinnerCountsAttr { get; set; }
        public virtual DbSet<T_SortTypesAttr> T_SortTypesAttr { get; set; }
    }
}
