//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCYN.Winform.Model.MeiTuan.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_City
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string URL { get; set; }
        public string MeiShiURL { get; set; }
        public Nullable<bool> State { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
    }
}
