<?xml version="1.0" encoding="utf-8"?><Database Name="Meituan" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=Meituan;Integrated Security=True" SettingsObjectName="XCYN.Winform.Properties.Settings" SettingsPropertyName="MeituanConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.T_Category" Member="T_Category">
    <Type Name="T_Category">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="url" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
</Database>