//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCYN.Linq.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class zcp_formula_category
    {
        public int id { get; set; }
        public string name { get; set; }
        public string formula_name { get; set; }
        public string type { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<System.DateTime> add_time { get; set; }
        public string nick_name { get; set; }
    }
}
