//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCYN.Linq.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class zcp_picture_category
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> click { get; set; }
        public Nullable<bool> is_vip { get; set; }
        public string prifix { get; set; }
        public Nullable<bool> state { get; set; }
        public Nullable<System.DateTime> add_time { get; set; }
    }
}
