//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCYN.Linq.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class article_attribute_field
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public article_attribute_field()
        {
            this.channel_field = new HashSet<channel_field>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string title { get; set; }
        public string control_type { get; set; }
        public string data_type { get; set; }
        public Nullable<int> data_length { get; set; }
        public Nullable<byte> data_place { get; set; }
        public string item_option { get; set; }
        public string default_value { get; set; }
        public Nullable<byte> is_required { get; set; }
        public Nullable<byte> is_password { get; set; }
        public Nullable<byte> is_html { get; set; }
        public Nullable<byte> editor_type { get; set; }
        public string valid_tip_msg { get; set; }
        public string valid_error_msg { get; set; }
        public string valid_pattern { get; set; }
        public Nullable<int> sort_id { get; set; }
        public Nullable<byte> is_sys { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<channel_field> channel_field { get; set; }
    }
}
