//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCYN.Linq.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class original_formula_hito
    {
        public Nullable<int> hit_type { get; set; }
        public int formu_id { get; set; }
        public string user { get; set; }
        public string formu_name { get; set; }
        public string right { get; set; }
        public string accuracy { get; set; }
    }
}
