//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCYN.Linq.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_space_log
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> visit_id { get; set; }
        public Nullable<System.DateTime> add_time { get; set; }
        public Nullable<int> state { get; set; }
        public string user_name { get; set; }
        public string visit_name { get; set; }
        public string users_avatar { get; set; }
    }
}
