//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCYN.Linq.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class zcp_users
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string login_ip { get; set; }
        public Nullable<System.DateTime> login_time { get; set; }
        public string last_login_ip { get; set; }
        public Nullable<System.DateTime> last_login_time { get; set; }
        public Nullable<System.DateTime> exit_time { get; set; }
        public string message { get; set; }
        public Nullable<int> is_expert { get; set; }
        public Nullable<int> online_state { get; set; }
        public Nullable<System.DateTime> active_time { get; set; }
        public Nullable<int> rank { get; set; }
        public Nullable<int> gold { get; set; }
        public Nullable<bool> is_bindPhone { get; set; }
        public Nullable<bool> is_bindMail { get; set; }
        public string withdraw_password { get; set; }
        public Nullable<bool> is_update_nickName { get; set; }
        public Nullable<decimal> inter_hit_rate { get; set; }
        public Nullable<int> master_star { get; set; }
        public Nullable<int> is_master { get; set; }
    }
}
