//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCYN.EasyUI.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_vote_record
    {
        public int id { get; set; }
        public Nullable<int> option_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<System.DateTime> add_time { get; set; }
        public string user_name { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public string num { get; set; }
        public string option_name { get; set; }
        public string type_name { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> type_id { get; set; }
    }
}
