//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCYN.Linq.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class zcp_attr_param_table
    {
        public int attr_seq { get; set; }
        public string para_name { get; set; }
        public string para_field { get; set; }
        public int pt_seq { get; set; }
        public Nullable<int> item_checked { get; set; }
        public Nullable<int> field_checked { get; set; }
    }
}
