//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCYN.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/XCYN.Service")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServiceFly")]
    public interface IServiceFly {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceFly/fly", ReplyAction="http://tempuri.org/IServiceFly/flyResponse")]
        XCYN.ServiceReference1.Student fly(XCYN.ServiceReference1.Student student);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IServiceFly/fly", ReplyAction="http://tempuri.org/IServiceFly/flyResponse")]
        System.IAsyncResult Beginfly(XCYN.ServiceReference1.Student student, System.AsyncCallback callback, object asyncState);
        
        XCYN.ServiceReference1.Student Endfly(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceFlyChannel : XCYN.ServiceReference1.IServiceFly, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class flyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public flyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public XCYN.ServiceReference1.Student Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((XCYN.ServiceReference1.Student)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceFlyClient : System.ServiceModel.ClientBase<XCYN.ServiceReference1.IServiceFly>, XCYN.ServiceReference1.IServiceFly {
        
        private BeginOperationDelegate onBeginflyDelegate;
        
        private EndOperationDelegate onEndflyDelegate;
        
        private System.Threading.SendOrPostCallback onflyCompletedDelegate;
        
        public ServiceFlyClient() {
        }
        
        public ServiceFlyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceFlyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceFlyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceFlyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<flyCompletedEventArgs> flyCompleted;
        
        public XCYN.ServiceReference1.Student fly(XCYN.ServiceReference1.Student student) {
            return base.Channel.fly(student);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult Beginfly(XCYN.ServiceReference1.Student student, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Beginfly(student, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public XCYN.ServiceReference1.Student Endfly(System.IAsyncResult result) {
            return base.Channel.Endfly(result);
        }
        
        private System.IAsyncResult OnBeginfly(object[] inValues, System.AsyncCallback callback, object asyncState) {
            XCYN.ServiceReference1.Student student = ((XCYN.ServiceReference1.Student)(inValues[0]));
            return this.Beginfly(student, callback, asyncState);
        }
        
        private object[] OnEndfly(System.IAsyncResult result) {
            XCYN.ServiceReference1.Student retVal = this.Endfly(result);
            return new object[] {
                    retVal};
        }
        
        private void OnflyCompleted(object state) {
            if ((this.flyCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.flyCompleted(this, new flyCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void flyAsync(XCYN.ServiceReference1.Student student) {
            this.flyAsync(student, null);
        }
        
        public void flyAsync(XCYN.ServiceReference1.Student student, object userState) {
            if ((this.onBeginflyDelegate == null)) {
                this.onBeginflyDelegate = new BeginOperationDelegate(this.OnBeginfly);
            }
            if ((this.onEndflyDelegate == null)) {
                this.onEndflyDelegate = new EndOperationDelegate(this.OnEndfly);
            }
            if ((this.onflyCompletedDelegate == null)) {
                this.onflyCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnflyCompleted);
            }
            base.InvokeAsync(this.onBeginflyDelegate, new object[] {
                        student}, this.onEndflyDelegate, this.onflyCompletedDelegate, userState);
        }
    }
}
