//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCYN.EasyUI.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_collect_count
    {
        public int id { get; set; }
        public Nullable<int> channel_id { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<int> post_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<System.DateTime> add_time { get; set; }
        public Nullable<int> Expr1 { get; set; }
        public Nullable<int> Expr2 { get; set; }
        public Nullable<int> Expr3 { get; set; }
        public string title { get; set; }
        public string zhaiyao { get; set; }
        public string content { get; set; }
        public Nullable<int> click { get; set; }
        public Nullable<byte> is_red { get; set; }
        public Nullable<byte> status { get; set; }
        public string user_name { get; set; }
        public Nullable<System.DateTime> Expr4 { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public Nullable<bool> is_dailyHot { get; set; }
        public Nullable<System.DateTime> dailyHot_time { get; set; }
        public Nullable<bool> is_hotTopic { get; set; }
        public Nullable<System.DateTime> hotTopic_time { get; set; }
        public Nullable<bool> is_popularHot { get; set; }
        public Nullable<System.DateTime> popularHot_time { get; set; }
        public Nullable<int> Expr5 { get; set; }
        public Nullable<int> point { get; set; }
        public Nullable<int> collect_count { get; set; }
        public Nullable<int> great_count { get; set; }
    }
}
