//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCYN.EasyUI.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class zcp_limit_cheap
    {
        public int id { get; set; }
        public Nullable<int> formula_id { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<bool> formula_home { get; set; }
        public Nullable<bool> info_home { get; set; }
        public Nullable<bool> today_special { get; set; }
        public Nullable<bool> hot_special { get; set; }
        public Nullable<bool> special_formula { get; set; }
        public Nullable<bool> special_info { get; set; }
        public Nullable<bool> last_formula { get; set; }
        public Nullable<bool> last_info { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<System.DateTime> add_time { get; set; }
    }
}
