//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCYN.EasyUI.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class zcp_form_hitrate
    {
        public int id { get; set; }
        public Nullable<int> formula_id { get; set; }
        public string formula_level { get; set; }
        public Nullable<int> hits_number { get; set; }
        public Nullable<int> formula_number { get; set; }
        public Nullable<int> user_id { get; set; }
        public string kill_in_code { get; set; }
        public Nullable<bool> state { get; set; }
        public Nullable<System.DateTime> add_time { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
    }
}
