//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCYN.Print.AllServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AllServiceReference.IAllService")]
    public interface IAllService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockService/GetPrice", ReplyAction="http://tempuri.org/IStockService/GetPriceResponse")]
        double GetPrice(string ticker);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockService/GetPrice", ReplyAction="http://tempuri.org/IStockService/GetPriceResponse")]
        System.Threading.Tasks.Task<double> GetPriceAsync(string ticker);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IStockService/DoBigAnalysisFast")]
        void DoBigAnalysisFast();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IStockService/DoBigAnalysisFast")]
        System.Threading.Tasks.Task DoBigAnalysisFastAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockService/DoBigAnslysisSlow", ReplyAction="http://tempuri.org/IStockService/DoBigAnslysisSlowResponse")]
        void DoBigAnslysisSlow();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockService/DoBigAnslysisSlow", ReplyAction="http://tempuri.org/IStockService/DoBigAnslysisSlowResponse")]
        System.Threading.Tasks.Task DoBigAnslysisSlowAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/GetOrder", ReplyAction="http://tempuri.org/IOrderService/GetOrderResponse")]
        double GetOrder(string ticker);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/GetOrder", ReplyAction="http://tempuri.org/IOrderService/GetOrderResponse")]
        System.Threading.Tasks.Task<double> GetOrderAsync(string ticker);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAllServiceChannel : XCYN.Print.AllServiceReference.IAllService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AllServiceClient : System.ServiceModel.ClientBase<XCYN.Print.AllServiceReference.IAllService>, XCYN.Print.AllServiceReference.IAllService {
        
        public AllServiceClient() {
        }
        
        public AllServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AllServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AllServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AllServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double GetPrice(string ticker) {
            return base.Channel.GetPrice(ticker);
        }
        
        public System.Threading.Tasks.Task<double> GetPriceAsync(string ticker) {
            return base.Channel.GetPriceAsync(ticker);
        }
        
        public void DoBigAnalysisFast() {
            base.Channel.DoBigAnalysisFast();
        }
        
        public System.Threading.Tasks.Task DoBigAnalysisFastAsync() {
            return base.Channel.DoBigAnalysisFastAsync();
        }
        
        public void DoBigAnslysisSlow() {
            base.Channel.DoBigAnslysisSlow();
        }
        
        public System.Threading.Tasks.Task DoBigAnslysisSlowAsync() {
            return base.Channel.DoBigAnslysisSlowAsync();
        }
        
        public double GetOrder(string ticker) {
            return base.Channel.GetOrder(ticker);
        }
        
        public System.Threading.Tasks.Task<double> GetOrderAsync(string ticker) {
            return base.Channel.GetOrderAsync(ticker);
        }
    }
}
