//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCYN.Linq.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class attr_table_by_year
    {
        public int attr_seq { get; set; }
        public string item_name { get; set; }
        public string para_name { get; set; }
        public Nullable<int> attr_value { get; set; }
        public Nullable<int> mod { get; set; }
        public string cor_lottery_ball { get; set; }
    }
}
