//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCYN.EasyUI.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class link
    {
        public int id { get; set; }
        public string site_path { get; set; }
        public string title { get; set; }
        public string user_name { get; set; }
        public string user_tel { get; set; }
        public string email { get; set; }
        public string site_url { get; set; }
        public string img_url { get; set; }
        public int is_image { get; set; }
        public int sort_id { get; set; }
        public byte is_red { get; set; }
        public byte is_lock { get; set; }
        public Nullable<System.DateTime> add_time { get; set; }
    }
}
