//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCYN.EasyUI.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class article_attribute_value
    {
        public int article_id { get; set; }
        public string sub_title { get; set; }
        public string source { get; set; }
        public string author { get; set; }
        public string goods_no { get; set; }
        public Nullable<int> stock_quantity { get; set; }
        public Nullable<decimal> market_price { get; set; }
        public Nullable<decimal> sell_price { get; set; }
        public Nullable<int> point { get; set; }
        public string video_src { get; set; }
        public string xm { get; set; }
        public string name_pic { get; set; }
        public string pic02 { get; set; }
        public string name01 { get; set; }
        public string con01 { get; set; }
        public Nullable<int> great_number { get; set; }
        public string s_date { get; set; }
        public Nullable<int> kj_qs { get; set; }
        public string 搅珠日期 { get; set; }
        public string kj_zm1 { get; set; }
        public string kj_zm2 { get; set; }
        public string kj_zm3 { get; set; }
        public string kj_zm4 { get; set; }
        public string kj_zm5 { get; set; }
        public string kj_zm6 { get; set; }
        public string kj_tm { get; set; }
        public string jzzl_username { get; set; }
        public string jzzl_nf { get; set; }
        public Nullable<int> jzzl_qs { get; set; }
    
        public virtual article article { get; set; }
    }
}
