//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCYN.EasyUI.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class channel_site
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public channel_site()
        {
            this.channels = new HashSet<channel>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string build_path { get; set; }
        public string templet_path { get; set; }
        public string domain { get; set; }
        public string name { get; set; }
        public string logo { get; set; }
        public string company { get; set; }
        public string address { get; set; }
        public string tel { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string crod { get; set; }
        public string copyright { get; set; }
        public string seo_title { get; set; }
        public string seo_keyword { get; set; }
        public string seo_description { get; set; }
        public Nullable<byte> is_default { get; set; }
        public Nullable<int> sort_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<channel> channels { get; set; }
    }
}
