//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCYN.EasyUI.model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MeetingSysEntities : DbContext
    {
        public MeetingSysEntities()
            : base("name=MeetingSysEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<article> articles { get; set; }
        public virtual DbSet<article_albums> article_albums { get; set; }
        public virtual DbSet<article_attach> article_attach { get; set; }
        public virtual DbSet<article_attribute_field> article_attribute_field { get; set; }
        public virtual DbSet<article_attribute_value> article_attribute_value { get; set; }
        public virtual DbSet<article_category> article_category { get; set; }
        public virtual DbSet<article_comment> article_comment { get; set; }
        public virtual DbSet<channel> channels { get; set; }
        public virtual DbSet<channel_field> channel_field { get; set; }
        public virtual DbSet<channel_site> channel_site { get; set; }
        public virtual DbSet<express> expresses { get; set; }
        public virtual DbSet<feedback> feedbacks { get; set; }
        public virtual DbSet<formu_rank_config> formu_rank_config { get; set; }
        public virtual DbSet<link> links { get; set; }
        public virtual DbSet<mail_template> mail_template { get; set; }
        public virtual DbSet<manager> managers { get; set; }
        public virtual DbSet<manager_log> manager_log { get; set; }
        public virtual DbSet<manager_role> manager_role { get; set; }
        public virtual DbSet<manager_role_value> manager_role_value { get; set; }
        public virtual DbSet<navigation> navigations { get; set; }
        public virtual DbSet<order_goods> order_goods { get; set; }
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<payment> payments { get; set; }
        public virtual DbSet<point> points { get; set; }
        public virtual DbSet<role_formu_list> role_formu_list { get; set; }
        public virtual DbSet<sms_template> sms_template { get; set; }
        public virtual DbSet<system_loop_config> system_loop_config { get; set; }
        public virtual DbSet<user_amount_log> user_amount_log { get; set; }
        public virtual DbSet<user_code> user_code { get; set; }
        public virtual DbSet<user_group_price> user_group_price { get; set; }
        public virtual DbSet<user_groups> user_groups { get; set; }
        public virtual DbSet<user_login_log> user_login_log { get; set; }
        public virtual DbSet<user_message> user_message { get; set; }
        public virtual DbSet<user_oauth> user_oauth { get; set; }
        public virtual DbSet<user_oauth_app> user_oauth_app { get; set; }
        public virtual DbSet<user_point_log> user_point_log { get; set; }
        public virtual DbSet<user_recharge> user_recharge { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<zcp_ads> zcp_ads { get; set; }
        public virtual DbSet<zcp_article_post_collect> zcp_article_post_collect { get; set; }
        public virtual DbSet<zcp_article_post_great> zcp_article_post_great { get; set; }
        public virtual DbSet<zcp_bank> zcp_bank { get; set; }
        public virtual DbSet<zcp_bank_account> zcp_bank_account { get; set; }
        public virtual DbSet<zcp_bank_transfer> zcp_bank_transfer { get; set; }
        public virtual DbSet<zcp_bbs_cate_ext> zcp_bbs_cate_ext { get; set; }
        public virtual DbSet<zcp_bookmark> zcp_bookmark { get; set; }
        public virtual DbSet<zcp_cheap_time> zcp_cheap_time { get; set; }
        public virtual DbSet<zcp_collect_account> zcp_collect_account { get; set; }
        public virtual DbSet<zcp_database> zcp_database { get; set; }
        public virtual DbSet<zcp_exp> zcp_exp { get; set; }
        public virtual DbSet<zcp_exp_detail> zcp_exp_detail { get; set; }
        public virtual DbSet<zcp_focus> zcp_focus { get; set; }
        public virtual DbSet<zcp_form_hitrate> zcp_form_hitrate { get; set; }
        public virtual DbSet<zcp_formu_order> zcp_formu_order { get; set; }
        public virtual DbSet<zcp_formula_click> zcp_formula_click { get; set; }
        public virtual DbSet<zcp_formula_coefficient> zcp_formula_coefficient { get; set; }
        public virtual DbSet<zcp_formula_collect> zcp_formula_collect { get; set; }
        public virtual DbSet<zcp_formula_comment> zcp_formula_comment { get; set; }
        public virtual DbSet<zcp_formula_commentpraise> zcp_formula_commentpraise { get; set; }
        public virtual DbSet<zcp_formula_ext> zcp_formula_ext { get; set; }
        public virtual DbSet<zcp_formula_rank> zcp_formula_rank { get; set; }
        public virtual DbSet<zcp_formula_reward> zcp_formula_reward { get; set; }
        public virtual DbSet<zcp_help> zcp_help { get; set; }
        public virtual DbSet<zcp_help_cate> zcp_help_cate { get; set; }
        public virtual DbSet<zcp_info_ext> zcp_info_ext { get; set; }
        public virtual DbSet<zcp_info_small> zcp_info_small { get; set; }
        public virtual DbSet<zcp_integral_formula_category> zcp_integral_formula_category { get; set; }
        public virtual DbSet<zcp_integral_info_category> zcp_integral_info_category { get; set; }
        public virtual DbSet<zcp_invite> zcp_invite { get; set; }
        public virtual DbSet<zcp_limit_cheap> zcp_limit_cheap { get; set; }
        public virtual DbSet<zcp_lottery_data> zcp_lottery_data { get; set; }
        public virtual DbSet<zcp_lottery_record> zcp_lottery_record { get; set; }
        public virtual DbSet<zcp_mail> zcp_mail { get; set; }
        public virtual DbSet<zcp_member> zcp_member { get; set; }
        public virtual DbSet<zcp_member_exp> zcp_member_exp { get; set; }
        public virtual DbSet<zcp_member_point> zcp_member_point { get; set; }
        public virtual DbSet<zcp_member_reward> zcp_member_reward { get; set; }
        public virtual DbSet<zcp_member_right> zcp_member_right { get; set; }
        public virtual DbSet<zcp_member_signIn> zcp_member_signIn { get; set; }
        public virtual DbSet<zcp_message> zcp_message { get; set; }
        public virtual DbSet<zcp_note_bookmark> zcp_note_bookmark { get; set; }
        public virtual DbSet<zcp_notebook> zcp_notebook { get; set; }
        public virtual DbSet<zcp_operating_statement> zcp_operating_statement { get; set; }
        public virtual DbSet<zcp_order> zcp_order { get; set; }
        public virtual DbSet<zcp_para> zcp_para { get; set; }
        public virtual DbSet<zcp_picture> zcp_picture { get; set; }
        public virtual DbSet<zcp_picture_bookmark> zcp_picture_bookmark { get; set; }
        public virtual DbSet<zcp_picture_category> zcp_picture_category { get; set; }
        public virtual DbSet<zcp_picture_collect> zcp_picture_collect { get; set; }
        public virtual DbSet<zcp_picture_ext> zcp_picture_ext { get; set; }
        public virtual DbSet<zcp_picture_search> zcp_picture_search { get; set; }
        public virtual DbSet<zcp_point> zcp_point { get; set; }
        public virtual DbSet<zcp_point_log> zcp_point_log { get; set; }
        public virtual DbSet<zcp_post> zcp_post { get; set; }
        public virtual DbSet<zcp_post_collect> zcp_post_collect { get; set; }
        public virtual DbSet<zcp_post_great> zcp_post_great { get; set; }
        public virtual DbSet<zcp_post_recommend> zcp_post_recommend { get; set; }
        public virtual DbSet<zcp_rank> zcp_rank { get; set; }
        public virtual DbSet<zcp_recommend> zcp_recommend { get; set; }
        public virtual DbSet<zcp_record_bigClass> zcp_record_bigClass { get; set; }
        public virtual DbSet<zcp_record_smallClass> zcp_record_smallClass { get; set; }
        public virtual DbSet<zcp_record_yearClass> zcp_record_yearClass { get; set; }
        public virtual DbSet<zcp_reward_detail> zcp_reward_detail { get; set; }
        public virtual DbSet<zcp_space_log> zcp_space_log { get; set; }
        public virtual DbSet<zcp_superior> zcp_superior { get; set; }
        public virtual DbSet<zcp_test> zcp_test { get; set; }
        public virtual DbSet<zcp_third_account> zcp_third_account { get; set; }
        public virtual DbSet<zcp_third_party> zcp_third_party { get; set; }
        public virtual DbSet<zcp_third_transfer> zcp_third_transfer { get; set; }
        public virtual DbSet<zcp_users> zcp_users { get; set; }
        public virtual DbSet<zcp_users_vip> zcp_users_vip { get; set; }
        public virtual DbSet<zcp_vote_option> zcp_vote_option { get; set; }
        public virtual DbSet<zcp_vote_record> zcp_vote_record { get; set; }
        public virtual DbSet<zcp_vote_type> zcp_vote_type { get; set; }
        public virtual DbSet<attr_param_table> attr_param_table { get; set; }
        public virtual DbSet<attr_table_by_year> attr_table_by_year { get; set; }
        public virtual DbSet<ballnum_attrValue_map> ballnum_attrValue_map { get; set; }
        public virtual DbSet<duplic_param_table> duplic_param_table { get; set; }
        public virtual DbSet<formu_lichun_date> formu_lichun_date { get; set; }
        public virtual DbSet<Gregorian_lunar_map> Gregorian_lunar_map { get; set; }
        public virtual DbSet<LunisolarData> LunisolarDatas { get; set; }
        public virtual DbSet<LunisolarSolarTerm> LunisolarSolarTerms { get; set; }
        public virtual DbSet<original_formula_hito> original_formula_hito { get; set; }
        public virtual DbSet<solardata> solardatas { get; set; }
        public virtual DbSet<user_attach_log> user_attach_log { get; set; }
        public virtual DbSet<whan_ball_attr_table> whan_ball_attr_table { get; set; }
        public virtual DbSet<zcp_attr_param_table> zcp_attr_param_table { get; set; }
        public virtual DbSet<zcp_attr_param_table_bak> zcp_attr_param_table_bak { get; set; }
        public virtual DbSet<zcp_attr_param_table2> zcp_attr_param_table2 { get; set; }
        public virtual DbSet<zcp_attr_relation_table> zcp_attr_relation_table { get; set; }
        public virtual DbSet<zcp_ballnum_attrValue_map> zcp_ballnum_attrValue_map { get; set; }
        public virtual DbSet<zcp_bank_withdrawal> zcp_bank_withdrawal { get; set; }
        public virtual DbSet<zcp_combin_formula_list> zcp_combin_formula_list { get; set; }
        public virtual DbSet<zcp_comment> zcp_comment { get; set; }
        public virtual DbSet<zcp_direction> zcp_direction { get; set; }
        public virtual DbSet<zcp_formula> zcp_formula { get; set; }
        public virtual DbSet<zcp_formula_accuracy> zcp_formula_accuracy { get; set; }
        public virtual DbSet<zcp_formula_bookmark> zcp_formula_bookmark { get; set; }
        public virtual DbSet<zcp_formula_category> zcp_formula_category { get; set; }
        public virtual DbSet<zcp_formula_list> zcp_formula_list { get; set; }
        public virtual DbSet<zcp_formula_list2> zcp_formula_list2 { get; set; }
        public virtual DbSet<zcp_formula_point> zcp_formula_point { get; set; }
        public virtual DbSet<zcp_formula_praise> zcp_formula_praise { get; set; }
        public virtual DbSet<zcp_formula_small> zcp_formula_small { get; set; }
        public virtual DbSet<zcp_info> zcp_info { get; set; }
        public virtual DbSet<zcp_info_accuracy> zcp_info_accuracy { get; set; }
        public virtual DbSet<zcp_info_bookmark> zcp_info_bookmark { get; set; }
        public virtual DbSet<zcp_info_category> zcp_info_category { get; set; }
        public virtual DbSet<zcp_info_click> zcp_info_click { get; set; }
        public virtual DbSet<zcp_info_coefficient> zcp_info_coefficient { get; set; }
        public virtual DbSet<zcp_info_collect> zcp_info_collect { get; set; }
        public virtual DbSet<zcp_info_comment> zcp_info_comment { get; set; }
        public virtual DbSet<zcp_info_commentpraise> zcp_info_commentpraise { get; set; }
        public virtual DbSet<zcp_info_hitrate> zcp_info_hitrate { get; set; }
        public virtual DbSet<zcp_info_order> zcp_info_order { get; set; }
        public virtual DbSet<zcp_info_point> zcp_info_point { get; set; }
        public virtual DbSet<zcp_info_praise> zcp_info_praise { get; set; }
        public virtual DbSet<zcp_info_rank> zcp_info_rank { get; set; }
        public virtual DbSet<zcp_info_reward> zcp_info_reward { get; set; }
        public virtual DbSet<zcp_lottery_bak> zcp_lottery_bak { get; set; }
        public virtual DbSet<zcp_SEQUENCE> zcp_SEQUENCE { get; set; }
        public virtual DbSet<zcp_sx_table> zcp_sx_table { get; set; }
        public virtual DbSet<zcp_whan_attr_table> zcp_whan_attr_table { get; set; }
        public virtual DbSet<ballnum_attrValue_map_view> ballnum_attrValue_map_view { get; set; }
        public virtual DbSet<v_collect> v_collect { get; set; }
        public virtual DbSet<v_collect_account> v_collect_account { get; set; }
        public virtual DbSet<v_collect_count> v_collect_count { get; set; }
        public virtual DbSet<v_focus> v_focus { get; set; }
        public virtual DbSet<v_formu_info_post> v_formu_info_post { get; set; }
        public virtual DbSet<v_formula_ext> v_formula_ext { get; set; }
        public virtual DbSet<v_get_exp_rank_tb> v_get_exp_rank_tb { get; set; }
        public virtual DbSet<v_info_ext> v_info_ext { get; set; }
        public virtual DbSet<v_invit> v_invit { get; set; }
        public virtual DbSet<v_last_lottery> v_last_lottery { get; set; }
        public virtual DbSet<v_limit_formula> v_limit_formula { get; set; }
        public virtual DbSet<v_limit_info> v_limit_info { get; set; }
        public virtual DbSet<v_my_comment> v_my_comment { get; set; }
        public virtual DbSet<v_picture> v_picture { get; set; }
        public virtual DbSet<v_post_expert> v_post_expert { get; set; }
        public virtual DbSet<v_post_list> v_post_list { get; set; }
        public virtual DbSet<v_recommend> v_recommend { get; set; }
        public virtual DbSet<v_shop_all> v_shop_all { get; set; }
        public virtual DbSet<v_space_log> v_space_log { get; set; }
        public virtual DbSet<v_ta_formula> v_ta_formula { get; set; }
        public virtual DbSet<v_ta_info> v_ta_info { get; set; }
        public virtual DbSet<v_users_ext> v_users_ext { get; set; }
        public virtual DbSet<v_vote_record> v_vote_record { get; set; }
        public virtual DbSet<view_channel_bbs> view_channel_bbs { get; set; }
        public virtual DbSet<view_channel_kj_info> view_channel_kj_info { get; set; }
        public virtual DbSet<view_formula_mode> view_formula_mode { get; set; }
        public virtual DbSet<view_role> view_role { get; set; }
        public virtual DbSet<view_select_param> view_select_param { get; set; }
        public virtual DbSet<view_zcp_order> view_zcp_order { get; set; }
    }
}
