//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCYN.EasyUI.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_formu_info_post
    {
        public int id { get; set; }
        public int category_id { get; set; }
        public string type { get; set; }
        public string name { get; set; }
        public string category_name { get; set; }
        public Nullable<System.DateTime> add_time { get; set; }
        public string hitinfo { get; set; }
        public int is_limit_cheap { get; set; }
        public Nullable<int> point { get; set; }
        public Nullable<int> special_point { get; set; }
        public Nullable<int> special_time { get; set; }
        public Nullable<int> click { get; set; }
        public string zhaiyao { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> comment_count { get; set; }
        public Nullable<int> great_count { get; set; }
    }
}
