//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCYN.EasyUI.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class zcp_ads
    {
        public int id { get; set; }
        public string module_name { get; set; }
        public string page_name { get; set; }
        public string page_url { get; set; }
        public string position { get; set; }
        public string size { get; set; }
        public string title { get; set; }
        public Nullable<int> max_length { get; set; }
        public string img_url { get; set; }
        public string link_url { get; set; }
        public string img_type { get; set; }
        public int type { get; set; }
        public Nullable<int> state { get; set; }
    }
}
