//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCYN.EasyUI.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class zcp_attr_relation_table
    {
        public Nullable<int> attr_item_No { get; set; }
        public string attr_item { get; set; }
        public string attr_name { get; set; }
        public Nullable<int> attr_value { get; set; }
        public string cor_lottery_num { get; set; }
        public Nullable<int> model_value { get; set; }
        public Nullable<int> follow_year_flag { get; set; }
        public string attr_year { get; set; }
    }
}
