//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCYN.EasyUI.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class zcp_mail
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public string user_name { get; set; }
        public string mail_title { get; set; }
        public string mail_content { get; set; }
        public System.DateTime mail_date { get; set; }
        public Nullable<int> receive_id { get; set; }
        public string receive_name { get; set; }
        public int state { get; set; }
        public Nullable<int> poststa { get; set; }
    }
}
