//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCYN.EasyUI.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class zcp_record_smallClass
    {
        public int id { get; set; }
        public int b_id { get; set; }
        public string name { get; set; }
        public string number { get; set; }
        public Nullable<int> type { get; set; }
        public string c_format { get; set; }
        public string c_type { get; set; }
        public Nullable<int> c_target { get; set; }
        public string c_output { get; set; }
        public string color { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<System.DateTime> add_time { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
    }
}
